name: Radar

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - name: Update globalConfgig
        run: |
          jq '.apiUrl = "${{ secrets.AWS_API_GATEWAY_URL }}" | .cognitoPoolID = "${{ secrets.REACT_APP_COGNITO_POOL_ID }}" | .cognitoClientID = "${{ secrets.REACT_APP_COGNITO_APP_CLIENT_ID }}"' src/globalConfig.json > config.tmp && mv -f config.tmp src/globalConfig.json
      - run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy build to S3
        run: |
          aws s3 sync ./build s3://${{ secrets.AWS_BUCKET_NAME }}/
